[server]
runOnSave = true
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false  # Disable usage statistics gathering
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#FF4B4B"  # Red color for recording button
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[runner]
fastReruns = true  # Enable fast re-runs for development