[server]
runOnSave = true

[theme]
primaryColor = "#FF4B4B"  # Red color for recording button
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false  # Disable usage statistics gathering